zookeeper:
  image: jplock/zookeeper:3.4.6
  name: zookeeper
  ports:
    - "2182:2181"
kafka:
  image: wurstmeister/kafka:0.8.2.0
  name: kafka
  hostname: kafka
  links:
   - zookeeper:zk
  environment:
    KAFKA_DEFAULT_TOPIC: "http-request"
    KAFKA_ADVERTISED_HOST_NAME: "kafka"
    KAFKA_ADVERTISED_PORT: 9092
  ports:
   - "9092:9092"
